apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  postgres-user: {{ .Values.secrets.postgres.user | b64enc }}
  postgres-password: {{ .Values.secrets.postgres.password | b64enc }} 