apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # These values are base64 encoded
  postgres-user: cG9zdGdyZXM=     # 'postgres' in base64
  postgres-password: cG9zdGdyZXM=  # 'postgres' in base64 